// The preserved Sina 2000 homepage supplies portal geometry; content remains 小红书.
export const document2000 = `
:host{all:initial;position:fixed;inset:0;z-index:2147483645;display:block;color-scheme:light;background:#fff;color:#111}
*{box-sizing:border-box;animation:none!important;transition:none!important;scroll-behavior:auto!important}
[hidden]{display:none!important}
main{position:absolute;inset:0;overflow:auto;overscroll-behavior:contain;padding:12px 12px 270px;font:12px/1.65 SimSun,"Songti SC",serif;text-align:left;color:#111;background:#fff;overflow-anchor:none}
.document{width:760px;min-width:760px;margin:0 auto;background:#fff}
h1{font-size:30px;line-height:1.2;margin:0;color:#c82713}h2{font-size:14px;line-height:24px;height:26px;margin:0 0 8px;padding:0 8px;background:#f3d679;border:1px solid #cbb277;color:#30305e}h3{font-size:12px;line-height:20px;margin:12px 0 6px;padding:0 5px;color:#30305e;background:#fff0b7;border-bottom:1px solid #cbb277}
p{margin:6px 0}a,a:link{color:#0000cc;text-decoration:underline;cursor:pointer}a:visited{color:#551a8b}a:hover,a:active{color:#c40000}a[aria-disabled=true]{color:#777;text-decoration:none;cursor:default}
button,input,select,textarea{font:12px/1.4 SimSun,"Songti SC",serif;color:#000;border-radius:0}button,input[type=submit]{padding:2px 8px;background:#ddd;border:2px outset #eee;cursor:pointer}button:active{border-style:inset}button:disabled{color:#777;cursor:default}input[type=search],input[type=text],textarea{appearance:none;background:#fff;border:2px inset #ddd;padding:2px 4px}input[type=search],input[type=text]{width:240px}textarea{display:block;width:100%;min-height:88px;resize:vertical}
form{margin:8px 0}form label{margin-right:8px}form button{margin-left:8px}form textarea+button{margin:8px 0}hr{border:0;border-top:1px solid #c7b98f;margin:12px 0}
nav{margin:8px 0;line-height:22px}nav a,nav button{margin-right:16px}nav a[data-nav=messages]{min-width:80px}
.portal-identity .era-brand{display:inline-flex;align-items:center;gap:6px;white-space:nowrap}.portal-masthead{border-bottom:1px solid #cbb277}.portal-identity{display:flex;align-items:center;gap:16px;min-height:58px;padding:5px 10px;background:#fffbed}.portal-identity>span{font:12px "Fusion Pixel 12px Monospaced SC",SimSun,serif;color:#555}.portal-identity>div{margin-left:auto}.portal-masthead>nav:not(.channel-matrix){margin:0;padding:3px 10px;background:#363363;color:#fff;min-height:30px}.portal-masthead>nav:not(.channel-matrix) a,.portal-masthead>nav:not(.channel-matrix) a:visited{color:#fff}.portal-masthead>nav:not(.channel-matrix) button{font-size:12px;padding:1px 6px}.portal-masthead>form{margin:0;padding:6px 10px;background:#f4e7b3;border:1px solid #cbb277;border-top:0}.channel-matrix{display:grid;grid-template-columns:repeat(4,1fr);gap:0;margin:0;padding:5px 10px;background:#fff8df;border:1px solid #cbb277;border-top:0}.channel-matrix [data-channel]{border:0;background:transparent;color:#0000cc;text-decoration:underline;padding:2px 5px;text-align:left;line-height:20px}.channel-matrix [data-channel]:disabled{font-weight:bold;color:#30305e;text-decoration:none}.channel-matrix [data-channel]:hover:not(:disabled){color:#c40000}
.portal-layout{display:flex;align-items:flex-start;gap:12px;margin-top:10px}.portal-side{flex:0 0 138px;min-width:138px;border:1px solid #cbb277;background:#fff4c7;padding:0 7px 8px}.portal-side>h2{margin:0 -7px 8px;border-width:0 0 1px}.portal-side>a{display:block;line-height:22px}.portal-content{flex:1;min-width:0}
.picture-guide{margin-bottom:12px}.guide-strip{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:0 8px 8px}.guide-item{text-align:center;min-width:0}.guide-item>.picture{border:0;padding:0;margin:0 auto;background:transparent}.guide-item .period-image-frame{margin:0 auto}.guide-item .picture figcaption{font-size:12px;line-height:17px;min-height:17px}.guide-caption{margin:3px 0 0;line-height:18px;overflow-wrap:anywhere}.guide-item img,.guide-item canvas{max-width:120px;max-height:80px}
table{width:100%;border-collapse:collapse;table-layout:fixed;font:12px/1.65 SimSun,"Songti SC",serif;margin:8px 0}th,td{border:1px solid #d0c199;padding:4px 7px;vertical-align:top;overflow-wrap:anywhere;text-align:left}th{font-weight:normal;background:#f3e3a8;color:#30305e}tbody tr:nth-child(even){background:#fffbef}.topic-table{margin-top:0}.topic-table th{height:26px}.topic-table td{padding-top:6px;padding-bottom:6px}.topic-table td a{line-height:18px}
.portal-article{margin:10px 0;padding:8px 20px 12px;border-bottom:1px solid #c7b98f}.portal-article .article-title{height:auto;background:transparent;border:0;color:#000;text-align:center;font-size:20px;line-height:1.45;margin:4px 0 10px;padding:0}.portal-article>.byline{text-align:center;font-size:12px;color:#555;padding-bottom:8px;border-bottom:1px solid #c7b98f}.portal-article>.body{font-size:14px;line-height:1.85;margin:16px 0}.body{white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px;line-height:1.8;margin:10px 0}.byline{font-size:12px;color:#555}.byline>span{margin-left:18px}
.portal-opinions{margin-top:14px}.opinion{margin:0 0 12px;border:1px solid #d0c199}.opinion>.byline{margin:0;padding:4px 8px;background:#fff0c3;border-bottom:1px solid #d0c199}.opinion>.body{padding:8px 10px;margin:0;font-size:14px}.portal-opinions>form{border-top:1px solid #cbb277;padding:10px 8px;background:#fffbed}.portal-profile{margin:10px 0 14px;padding:8px;border:1px solid #cbb277;background:#fffbed}.portal-profile>h2{margin:-8px -8px 8px;border-width:0 0 1px}.portal-profile>.picture{float:left;margin:0 12px 8px 0}.portal-profile:after{content:'';display:block;clear:both}
.picture{margin:10px 0;padding:4px;border:1px solid #c7b98f;background:#fffaf0;width:fit-content;max-width:100%}.picture figcaption{font-size:12px;margin:4px 0 0}.period-image-frame{max-width:100%;overflow:hidden;background:#ede7d5}.picture canvas,.picture img{display:block;max-width:100%;height:auto;object-fit:contain;image-rendering:auto}.portal-article .picture{margin-left:auto;margin-right:auto}
.mail-table .body{font-size:12px;margin:0}.mail-table button{max-width:100%;overflow-wrap:anywhere;text-align:left}[data-inbox] nav{background:#fff0c3;padding:3px 8px;border:1px solid #d0c199}[data-inbox] nav button{margin-right:6px}[data-inbox]>h3{margin-top:8px}.period-compose label{display:block;margin:0 0 8px}.period-compose textarea{margin-top:6px}.period-compose button{margin:4px 0}
.paging{min-height:28px;margin:12px 0;padding:5px 7px;background:#fff6df;border:1px solid #cbb277}.paging button,.paging a{margin-right:12px}.status{min-height:16px;margin:5px 0;color:#665537}.site-footer{text-align:center;font-size:12px;margin-top:14px}.site-footer button,.site-footer a{margin:0 8px}
.period-video{width:332px;max-width:100%;margin:14px auto;border:2px outset #ddd;background:#c0c0c0;padding:4px}.period-video>h3{margin:0 0 4px;background:#333366;color:#fff;border:0}.period-video canvas,.period-video video{display:block;width:320px;max-width:100%;background:#000}.period-video button,.period-video input{font-size:12px}.video-controls{display:flex;align-items:center;gap:8px;padding:6px 2px}.video-transport{display:flex;align-items:center;gap:6px;flex:1;min-width:0}.video-controls input[type=range]{appearance:none;min-width:0;flex:1;height:8px;border:2px inset #ddd;background:#aaa}.video-controls input[type=range]::-webkit-slider-thumb{appearance:none;width:11px;height:18px;background:#ccc;border:2px outset #eee;border-radius:0}.video-controls input[type=range]::-moz-range-thumb{width:8px;height:14px;background:#ccc;border:2px outset #eee;border-radius:0}.period-video>p{font-size:12px;margin:4px 2px}
a:focus-visible,button:focus-visible,input:focus-visible,textarea:focus-visible{outline:1px dotted #000;outline-offset:3px}
@media(max-width:784px){main{padding:12px 12px 270px}.document{margin:0}}
`;
